/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import excepciones.CampoVacio; 
import controlador.Main;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Javipaur
 */
public class ConsultaSolicitud extends javax.swing.JFrame {

    /**
     * Creates new form inscripciones
     */
    public ConsultaSolicitud() {
        initComponents();
         setLocationRelativeTo(null);
         Bienvenida.setLocation(32767, 32767);
         ConsultaSoliciud.setVisible(true);
         ConsultaSoliciud.setLocation(32767, 32767);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelGeneral = new javax.swing.JPanel();
        Bienvenida = new javax.swing.JPanel();
        Saludo = new javax.swing.JLabel();
        ConsultaSoliciud = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        EnviarSolicitud = new javax.swing.JButton();
        bBorrar = new javax.swing.JButton();
        Bsalir = new javax.swing.JButton();
        lMensaje = new javax.swing.JLabel();
        Tdni = new javax.swing.JFormattedTextField();
        TfechaNac = new javax.swing.JFormattedTextField();
        Logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        PanelGeneral.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        Saludo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Saludo.setText("Consulta Solicitud");

        jLabel1.setText("Fecha Nacimiento del Menor");

        jLabel2.setText("Dni Tutor");

        EnviarSolicitud.setText("Enviar");
        EnviarSolicitud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarSolicitudActionPerformed(evt);
            }
        });

        bBorrar.setText("Borrar");
        bBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarActionPerformed(evt);
            }
        });

        Bsalir.setText("Panel General");
        Bsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BsalirActionPerformed(evt);
            }
        });

        try {
            Tdni.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########?")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            TfechaNac.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        TfechaNac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfechaNacActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultaSoliciudLayout = new javax.swing.GroupLayout(ConsultaSoliciud);
        ConsultaSoliciud.setLayout(ConsultaSoliciudLayout);
        ConsultaSoliciudLayout.setHorizontalGroup(
            ConsultaSoliciudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaSoliciudLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultaSoliciudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultaSoliciudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tdni, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                    .addComponent(TfechaNac))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(ConsultaSoliciudLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ConsultaSoliciudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ConsultaSoliciudLayout.createSequentialGroup()
                        .addComponent(EnviarSolicitud)
                        .addGap(18, 18, 18)
                        .addComponent(bBorrar)
                        .addGap(26, 26, 26)
                        .addComponent(Bsalir)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        ConsultaSoliciudLayout.setVerticalGroup(
            ConsultaSoliciudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaSoliciudLayout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(ConsultaSoliciudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Tdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultaSoliciudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TfechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lMensaje, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConsultaSoliciudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bBorrar)
                    .addComponent(EnviarSolicitud)
                    .addComponent(Bsalir)))
        );

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/udalekuak (1).png"))); // NOI18N

        javax.swing.GroupLayout BienvenidaLayout = new javax.swing.GroupLayout(Bienvenida);
        Bienvenida.setLayout(BienvenidaLayout);
        BienvenidaLayout.setHorizontalGroup(
            BienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BienvenidaLayout.createSequentialGroup()
                .addGroup(BienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BienvenidaLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Saludo))
                    .addGroup(BienvenidaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ConsultaSoliciud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BienvenidaLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        BienvenidaLayout.setVerticalGroup(
            BienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BienvenidaLayout.createSequentialGroup()
                .addComponent(Saludo, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ConsultaSoliciud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelGeneralLayout = new javax.swing.GroupLayout(PanelGeneral);
        PanelGeneral.setLayout(PanelGeneralLayout);
        PanelGeneralLayout.setHorizontalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addComponent(Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelGeneralLayout.setVerticalGroup(
            PanelGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelGeneralLayout.createSequentialGroup()
                .addComponent(Bienvenida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelGeneral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EnviarSolicitudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnviarSolicitudActionPerformed
       try{
         if(TfechaNac.getText().isEmpty())
            throw new CampoVacio();
          SimpleDateFormat sdt=new SimpleDateFormat("dd/MM/yyyy");
           sdt.setLenient(false);
           Date fecNac= sdt.parse(TfechaNac.getText());
        if(Tdni.getText().isEmpty())
            throw new CampoVacio();
        Main.MostrarConsultasolicitud(Tdni.getText(),TfechaNac.getText());
        BorrarConsultaSolicitud();
       }catch(ParseException e){JOptionPane.showMessageDialog(this,"Error en fecha nacimiento");
       }catch(CampoVacio e){JOptionPane.showMessageDialog(this,"Tienes que teclear algo"); 
       }catch(Exception e){JOptionPane.showMessageDialog(this,"Error en el sistema!");
       }
    }//GEN-LAST:event_EnviarSolicitudActionPerformed

    private void BsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BsalirActionPerformed
        Main.VolverPanelGeneral();
    }//GEN-LAST:event_BsalirActionPerformed

    private void bBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarActionPerformed
      BorrarConsultaSolicitud();
      
    }//GEN-LAST:event_bBorrarActionPerformed

    private void TfechaNacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfechaNacActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TfechaNacActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultaSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultaSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultaSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultaSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultaSolicitud().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bienvenida;
    private javax.swing.JButton Bsalir;
    private javax.swing.JPanel ConsultaSoliciud;
    private javax.swing.JButton EnviarSolicitud;
    private javax.swing.JLabel Logo;
    private javax.swing.JPanel PanelGeneral;
    private javax.swing.JLabel Saludo;
    private javax.swing.JFormattedTextField Tdni;
    private javax.swing.JFormattedTextField TfechaNac;
    private javax.swing.JButton bBorrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lMensaje;
    // End of variables declaration//GEN-END:variables

    private void BorrarConsultaSolicitud() {
           Tdni.setValue(null);
           TfechaNac.setValue(null);
    }
}
