/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import excepciones.LetraNoValida;
import controlador.Main;
import excepciones.CampoVacio;
//import java.sql.Date;
import java.util.Date;
import java.sql.SQLException;
import java.text.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Javipaur
 */
public class PanelSolicitud extends javax.swing.JFrame {
private int contadorMenor=1;
private int tel1,tel2,tel3,tel4;
private  Date fecNac;
    /**
     * Creates new form Solicitud
     */
    public PanelSolicitud() {
        initComponents();
        setLocationRelativeTo(null);
        lContador.setText(String.valueOf(contadorMenor));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JpanelTutor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tNombreT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tApellido1T = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tApellido2T = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        tCalleT = new javax.swing.JTextField();
        tNumeroT = new javax.swing.JTextField();
        tPisoT = new javax.swing.JTextField();
        tLetraT = new javax.swing.JTextField();
        tProvinciaT = new javax.swing.JTextField();
        tCodigopostalT = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        tMunicipioT = new javax.swing.JTextField();
        tTelefono1T = new javax.swing.JFormattedTextField();
        tTelefono2T = new javax.swing.JFormattedTextField();
        tTelefono3T = new javax.swing.JFormattedTextField();
        tTelefono4T = new javax.swing.JFormattedTextField();
        tDniT = new javax.swing.JFormattedTextField();
        JpanelMenor = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tApellido1P = new javax.swing.JTextField();
        tNombreP = new javax.swing.JTextField();
        tApellido2P = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        tCalleP = new javax.swing.JTextField();
        tNumeroP = new javax.swing.JTextField();
        tPisoP = new javax.swing.JTextField();
        tLetraP = new javax.swing.JTextField();
        tMunicipioP = new javax.swing.JTextField();
        tProvinciaP = new javax.swing.JTextField();
        tCodigoPostaP = new javax.swing.JTextField();
        tCentroP = new javax.swing.JTextField();
        tModeloP = new javax.swing.JTextField();
        bOtroMenor = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        lContador = new javax.swing.JLabel();
        tDniP = new javax.swing.JFormattedTextField();
        tfechaNacimientoP = new javax.swing.JFormattedTextField();
        Bborrar = new javax.swing.JButton();
        Baceptar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setUndecorated(true);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/udalekuak (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText(" Alta de Solicitud ");

        JpanelTutor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Padre / Madre / Tutor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel3.setText("Nombre");

        jLabel4.setText("Apellido 1");

        jLabel5.setText("Apellido 2");

        jLabel6.setText("Dni / Nif");

        jLabel20.setText("Calle");

        jLabel21.setText("Nº");

        jLabel22.setText("Piso");

        jLabel23.setText("Letra");

        jLabel24.setText("Provincia");

        jLabel25.setText("CP");

        jLabel27.setText("Telefonos:");

        jLabel26.setText("Municipio");

        try {
            tTelefono1T.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tTelefono2T.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tTelefono3T.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tTelefono4T.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tDniT.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########?")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        tDniT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tDniTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JpanelTutorLayout = new javax.swing.GroupLayout(JpanelTutor);
        JpanelTutor.setLayout(JpanelTutorLayout);
        JpanelTutorLayout.setHorizontalGroup(
            JpanelTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelTutorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelTutorLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tMunicipioT, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tProvinciaT, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tCodigopostalT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpanelTutorLayout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tTelefono1T, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tTelefono2T, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tTelefono3T, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tTelefono4T, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JpanelTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JpanelTutorLayout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tNombreT, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(5, 5, 5)
                            .addComponent(jLabel4)
                            .addGap(3, 3, 3)
                            .addComponent(tApellido1T))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, JpanelTutorLayout.createSequentialGroup()
                            .addGroup(JpanelTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelTutorLayout.createSequentialGroup()
                                    .addComponent(jLabel20)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tCalleT, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(JpanelTutorLayout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tApellido2T, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(JpanelTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(JpanelTutorLayout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tDniT))
                                .addGroup(JpanelTutorLayout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tNumeroT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tPisoT, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel23)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tLetraT, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpanelTutorLayout.setVerticalGroup(
            JpanelTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelTutorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JpanelTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tNombreT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(tApellido1T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(JpanelTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tApellido2T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6)
                        .addComponent(tDniT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(JpanelTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(tCalleT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNumeroT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tPisoT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLetraT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jLabel25)
                    .addComponent(tProvinciaT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCodigopostalT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tMunicipioT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(JpanelTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelTutorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tTelefono1T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tTelefono2T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tTelefono3T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tTelefono4T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        JpanelMenor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Participante", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel7.setText("Nombre");

        jLabel8.setText("Apellido 1");

        jLabel9.setText("Apellido 2");

        jLabel10.setText("Dni");

        jLabel11.setText("Calle");

        jLabel12.setText("Nº");

        jLabel13.setText("Piso");

        jLabel14.setText("Letra");

        jLabel15.setText("Municipio");

        jLabel16.setText("Provincia");

        jLabel17.setText("CP");

        jLabel18.setText("Centro");

        jLabel19.setText("Modelo");

        bOtroMenor.setText("Incluir otro participante");
        bOtroMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOtroMenorActionPerformed(evt);
            }
        });

        jLabel28.setText("Fecha Nacimiento");

        lContador.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lContador.setText("1");

        try {
            tDniP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########?")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            tfechaNacimientoP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout JpanelMenorLayout = new javax.swing.GroupLayout(JpanelMenor);
        JpanelMenor.setLayout(JpanelMenorLayout);
        JpanelMenorLayout.setHorizontalGroup(
            JpanelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelMenorLayout.createSequentialGroup()
                .addGroup(JpanelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JpanelMenorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(JpanelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JpanelMenorLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tMunicipioP, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tProvinciaP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tCodigoPostaP, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(JpanelMenorLayout.createSequentialGroup()
                                .addGroup(JpanelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(JpanelMenorLayout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tCentroP, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tModeloP, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(JpanelMenorLayout.createSequentialGroup()
                                        .addGroup(JpanelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(JpanelMenorLayout.createSequentialGroup()
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tCalleP))
                                            .addGroup(JpanelMenorLayout.createSequentialGroup()
                                                .addComponent(jLabel9)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tApellido2P, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(JpanelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JpanelMenorLayout.createSequentialGroup()
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tNumeroP, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel14)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tLetraP, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(JpanelMenorLayout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tDniP, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(18, 18, 18)
                                        .addGroup(JpanelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(JpanelMenorLayout.createSequentialGroup()
                                                .addComponent(jLabel13)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tPisoP, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(JpanelMenorLayout.createSequentialGroup()
                                                .addComponent(jLabel28)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(tfechaNacimientoP, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(JpanelMenorLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tApellido1P, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 207, Short.MAX_VALUE))))
                    .addComponent(bOtroMenor)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpanelMenorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lContador)))
                .addContainerGap())
        );
        JpanelMenorLayout.setVerticalGroup(
            JpanelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpanelMenorLayout.createSequentialGroup()
                .addComponent(lContador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JpanelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(tApellido1P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tApellido2P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel28)
                    .addComponent(tDniP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfechaNacimientoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JpanelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(tCalleP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tNumeroP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tLetraP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(tPisoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JpanelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(tProvinciaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tCodigoPostaP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tMunicipioP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(JpanelMenorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(tCentroP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tModeloP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(bOtroMenor)
                .addGap(35, 35, 35))
        );

        Bborrar.setText("Borrar");
        Bborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BborrarActionPerformed(evt);
            }
        });

        Baceptar.setText("Aceptar");
        Baceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaceptarActionPerformed(evt);
            }
        });

        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(Baceptar)
                .addGap(112, 112, 112)
                .addComponent(Bborrar)
                .addGap(117, 117, 117)
                .addComponent(bSalir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JpanelTutor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JpanelMenor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(JpanelTutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(JpanelMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Baceptar)
                    .addComponent(Bborrar)
                    .addComponent(bSalir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bOtroMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOtroMenorActionPerformed

        if(datosCorrectos()==true){
            
            if(contadorMenor==1)
            {   
                Main.GenerarObjetoTutor(
                    tNombreT.getText(),
                    tApellido1T.getText(),
                    tApellido2T.getText(),
                    tDniT.getText(),
                    tCalleT.getText(),
                    tNumeroT.getText(),
                    tPisoT.getText(),
                    tLetraT.getText(),
                    tMunicipioT.getText(),
                    tProvinciaT.getText(),
                    tCodigopostalT.getText(),
                    tel1,tel2,tel3,tel4);
                Main.GenerarObjetoMenor1( 
                    tNombreP.getText(),
                    tApellido1P.getText(),
                    tApellido2P.getText(),
                    tDniP.getText(),
                    tfechaNacimientoP.getText(),
                    tCalleP.getText(),
                    tNumeroP.getText(),
                    tPisoP.getText(),
                    tLetraP.getText(),
                    tMunicipioP.getText(),
                    tProvinciaP.getText(),
                    tCodigoPostaP.getText(),
                    tCentroP.getText(),
                    tModeloP.getText());
                contadorMenor++;
                lContador.setText(String.valueOf(contadorMenor));
                ProtegerTutor();
                BorrarMenor();
             } else{
                    if(contadorMenor==2)
                   {
                       Main.GenerarObjetoMenor2(
                        tNombreP.getText(),
                        tApellido1P.getText(),
                        tApellido2P.getText(),
                        tDniP.getText(),
                        tfechaNacimientoP.getText(),
                        tCalleP.getText(),
                        tNumeroP.getText(),
                        tPisoP.getText(),
                        tLetraP.getText(),
                        tMunicipioP.getText(),
                        tProvinciaP.getText(),
                        tCodigoPostaP.getText(),
                        tCentroP.getText(),
                        tModeloP.getText());
                       
                       contadorMenor++;
                       lContador.setText(String.valueOf(contadorMenor));
                       bOtroMenor.setEnabled(false);
                       BorrarMenor();
                   }
            }
        }       
    }//GEN-LAST:event_bOtroMenorActionPerformed

    private void BborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BborrarActionPerformed
      BorrarMenor();
      BorrarTutor();
      DesprotegerMenor();
      DesprotegerTutor();
    }//GEN-LAST:event_BborrarActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
       System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    private void BaceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaceptarActionPerformed
    if(datosCorrectos()==true){  
        if(contadorMenor==1)
            {   
                Main.GenerarObjetoTutor(
                    tNombreT.getText(),
                    tApellido1T.getText(),
                    tApellido2T.getText(),
                    tDniT.getText(),
                    tCalleT.getText(),
                    tNumeroT.getText(),
                    tPisoT.getText(),
                    tLetraT.getText(),
                    tMunicipioT.getText(),
                    tProvinciaT.getText(),
                    tCodigopostalT.getText(),
                    tel1,tel2,tel3,tel4);
                Main.GenerarObjetoMenor1( 
                    tNombreP.getText(),
                    tApellido1P.getText(),
                    tApellido2P.getText(),
                    tDniP.getText(),
                    tfechaNacimientoP.getText(),
                    tCalleP.getText(),
                    tNumeroP.getText(),
                    tPisoP.getText(),
                    tLetraP.getText(),
                    tMunicipioP.getText(),
                    tProvinciaP.getText(),
                    tCodigoPostaP.getText(),
                    tCentroP.getText(),tModeloP.getText());
                    ProtegerMenor();
            }
        
          if(contadorMenor==2)
                   {
                       Main.GenerarObjetoMenor2(
                        tNombreP.getText(),
                        tApellido1P.getText(),
                        tApellido2P.getText(),
                        tDniP.getText(),
                        tfechaNacimientoP.getText(),
                        tCalleP.getText(),
                        tNumeroP.getText(),
                        tPisoP.getText(),
                        tLetraP.getText(),
                        tMunicipioP.getText(),
                        tProvinciaP.getText(),
                        tCodigoPostaP.getText(),
                        tCentroP.getText(),
                        tModeloP.getText());
                        ProtegerMenor();
                       
                   }
                
        if(contadorMenor==3)
          {
             Main.GenerarObjetoMenor3(tNombreP.getText(),
                        tApellido1P.getText(),
                        tApellido2P.getText(),
                        tDniP.getText(),
                        tfechaNacimientoP.getText(),
                        tCalleP.getText(),
                        tNumeroP.getText(),
                        tPisoP.getText(),
                        tLetraP.getText(),
                        tMunicipioP.getText(),
                        tProvinciaP.getText(),
                        tCodigoPostaP.getText(),
                        tCentroP.getText(),
                        tModeloP.getText());
             ProtegerMenor();
          } 
        try {
            Main.InsertarSolicitud(contadorMenor);
        } catch (SQLException ex) {
            Logger.getLogger(PanelSolicitud.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this,"AltaProcesada!");
        Main.MostrarPanelGeneral();
    }
    }//GEN-LAST:event_BaceptarActionPerformed

    private void tDniTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tDniTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tDniTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelSolicitud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelSolicitud().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Baceptar;
    private javax.swing.JButton Bborrar;
    private javax.swing.JPanel JpanelMenor;
    private javax.swing.JPanel JpanelTutor;
    private javax.swing.JButton bOtroMenor;
    private javax.swing.JButton bSalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lContador;
    private javax.swing.JTextField tApellido1P;
    private javax.swing.JTextField tApellido1T;
    private javax.swing.JTextField tApellido2P;
    private javax.swing.JTextField tApellido2T;
    private javax.swing.JTextField tCalleP;
    private javax.swing.JTextField tCalleT;
    private javax.swing.JTextField tCentroP;
    private javax.swing.JTextField tCodigoPostaP;
    private javax.swing.JTextField tCodigopostalT;
    private javax.swing.JFormattedTextField tDniP;
    private javax.swing.JFormattedTextField tDniT;
    private javax.swing.JTextField tLetraP;
    private javax.swing.JTextField tLetraT;
    private javax.swing.JTextField tModeloP;
    private javax.swing.JTextField tMunicipioP;
    private javax.swing.JTextField tMunicipioT;
    private javax.swing.JTextField tNombreP;
    private javax.swing.JTextField tNombreT;
    private javax.swing.JTextField tNumeroP;
    private javax.swing.JTextField tNumeroT;
    private javax.swing.JTextField tPisoP;
    private javax.swing.JTextField tPisoT;
    private javax.swing.JTextField tProvinciaP;
    private javax.swing.JTextField tProvinciaT;
    private javax.swing.JFormattedTextField tTelefono1T;
    private javax.swing.JFormattedTextField tTelefono2T;
    private javax.swing.JFormattedTextField tTelefono3T;
    private javax.swing.JFormattedTextField tTelefono4T;
    private javax.swing.JFormattedTextField tfechaNacimientoP;
    // End of variables declaration//GEN-END:variables

    private boolean datosCorrectos() {
        try{
           if(tNombreT.getText().isEmpty())
               throw new CampoVacio("Nombre Titular");
           if(tApellido1T.getText().isEmpty())
               throw new CampoVacio("Apellido1 Titular");
           if(tApellido2T.getText().isEmpty())
               throw new CampoVacio("Apellido2 Titular");
           if(tDniT.getValue()==null)
                throw new CampoVacio("Dni Titular");
           String letras="TRWAGMYFPDXBNJZSQVHLCKET";
           String dni = tDniT.getText().substring(0,8);
           char letra= tDniT.getText().charAt(8);
           Integer modulo=Integer.parseInt(dni)%23;
           // if(letra != (letras.charAt(modulo)))
           // throw new LetraNoValida();     
           if(tCalleT.getText().isEmpty())
               throw new CampoVacio("Calle Titular");
           if(tNumeroT.getText().isEmpty())
               throw new CampoVacio("Numero Titular");
           if(tPisoT.getText().isEmpty())
               throw new CampoVacio("Piso Titular");
           if(tLetraT.getText().isEmpty())
               throw new CampoVacio("Letra Titular");
           if(tMunicipioT.getText().isEmpty())
               throw new CampoVacio("Municipio Titular");
           if(tProvinciaT.getText().isEmpty())
               throw new CampoVacio("Provincia Titular");
           if(tCodigopostalT.getText().isEmpty())
               throw new CampoVacio("CodigoPostal Titular");
           if(tTelefono1T.getText().isEmpty())
               throw new CampoVacio("Telefono1 Titular");
             tel1=Integer.parseInt(tTelefono1T.getText());
           if(tTelefono2T.getText().isEmpty())
               throw new CampoVacio("Telefono2 Titular");
             tel2=Integer.parseInt(tTelefono2T.getText());
           if(tTelefono3T.getText().isEmpty())
               throw new CampoVacio("Telefono3 Titular");
             tel3=Integer.parseInt(tTelefono3T.getText());
           if(tTelefono4T.getText().isEmpty())
               throw new CampoVacio("Telefono4 Participante");
             tel4=Integer.parseInt(tTelefono4T.getText());
  
           //datos participante
           
           if(tNombreP.getText().isEmpty())
               throw new CampoVacio("Nombre Participante");
           if(tApellido1P.getText().isEmpty())
               throw new CampoVacio("Apellido1 Participante");
           if(tApellido2P.getText().isEmpty())
               throw new CampoVacio("Apellido2 Participante");
          //if(tDniP.getValue()==null)
               //throw new CampoVacio("Dni Participante");
           if(tfechaNacimientoP.getText().isEmpty())
               throw new CampoVacio("Fecha Nacimiento Participante");
           
           SimpleDateFormat sdt=new SimpleDateFormat("dd/MM/yyyy");
           sdt.setLenient(false);
           Date fecNac= sdt.parse(tfechaNacimientoP.getText());

           
           if(tCalleP.getText().isEmpty())
               throw new CampoVacio("Calle Participante");
           if(tNumeroP.getText().isEmpty())
               throw new CampoVacio("Numero Participante"); 
           if(tLetraP.getText().isEmpty())
               throw new CampoVacio("Letra Participante"); 
           if(tPisoP.getText().isEmpty())
               throw new CampoVacio("Piso Participante"); 
           if(tMunicipioP.getText().isEmpty())
               throw new CampoVacio("Municipio Participante"); 
           if(tProvinciaP.getText().isEmpty())
               throw new CampoVacio("Provincia Participante"); 
           if(tCodigoPostaP.getText().isEmpty())
               throw new CampoVacio("CodigoPostal Participante"); 
           if(tCentroP.getText().isEmpty())
               throw new CampoVacio("Centro Participante"); 
           if(tModeloP.getText().isEmpty())
               throw new CampoVacio("Modelo Participante"); 
           return true;
       }catch(ParseException e){JOptionPane.showMessageDialog(this,"Error en fecha nacimiento");
       return false;
       //}catch(LetraNoValida e){JOptionPane.showMessageDialog(this,"Letra no valida");
       //return false;             
       }catch(CampoVacio e){JOptionPane.showMessageDialog(this,e.getMensaje());
       return false;    
       }catch(Exception e){JOptionPane.showMessageDialog(this,"Error en el sistema! formulario Solicitud");
       return false;
       }
    }

    private void ProtegerTutor() {
       tNombreT.setEditable(false);
       tApellido1T.setEditable(false);
       tApellido2T.setEditable(false);
       tDniT.setEditable(false);
       tCalleT.setEditable(false);
       tNumeroT.setEditable(false);
       tPisoT.setEditable(false);
       tLetraT.setEditable(false);
       tMunicipioT.setEditable(false);
       tProvinciaT.setEditable(false);
       tCodigopostalT.setEditable(false);
       tTelefono1T.setEditable(false);
       tTelefono2T.setEditable(false);
       tTelefono3T.setEditable(false);
       tTelefono4T.setEditable(false);
           
    }

    private void BorrarMenor() {
           tNombreP.requestFocus();
           tNombreP.setText("");
           tApellido1P.setText("");
           tApellido2P.setText("");
           tDniP.setValue(null);
           tfechaNacimientoP.setValue(null);
           tCalleP.setText("");
           tNumeroP.setText("");
           tLetraP.setText("");
           tPisoP.setText("");
           tMunicipioP.setText("");
           tProvinciaP.setText("");
           tCodigoPostaP.setText(""); 
           tCentroP.setText("");
           tModeloP.setText("");
    }

    private void ProtegerMenor() {
           tNombreP.setEditable(false);
           tApellido1P.setEditable(false);
           tApellido2P.setEditable(false);
           tDniP.setEditable(false);
           tfechaNacimientoP.setEditable(false);
           tCalleP.setEditable(false);
           tNumeroP.setEditable(false);
           tLetraP.setEditable(false);
           tPisoP.setEditable(false);
           tMunicipioP.setEditable(false);
           tProvinciaP.setEditable(false);
           tCodigoPostaP.setEditable(false);
           tCentroP.setEditable(false);
           tModeloP.setEditable(false);
    }

    private void BorrarTutor() {
       tNombreT.setText("");
       tApellido1T.setText("");
       tApellido2T.setText("");
       tDniT.setValue(null);
       tCalleT.setText("");
       tNumeroT.setText("");
       tPisoT.setText("");
       tLetraT.setText("");
       tMunicipioT.setText("");
       tProvinciaT.setText("");
       tCodigopostalT.setText("");
       tTelefono1T.setValue(null);
       tTelefono2T.setValue(null);
       tTelefono3T.setValue(null);
       tTelefono4T.setValue(null);
 
    }

    private void DesprotegerMenor() {
           tNombreP.setEditable(true);
           tApellido1P.setEditable(true);
           tApellido2P.setEditable(true);
           tDniP.setEditable(true);
           tfechaNacimientoP.setEditable(true);
           tCalleP.setEditable(true);
           tNumeroP.setEditable(true);
           tLetraP.setEditable(true);
           tPisoP.setEditable(true);
           tMunicipioP.setEditable(true);
           tProvinciaP.setEditable(true);
           tCodigoPostaP.setEditable(true);
           tCentroP.setEditable(true);
           tModeloP.setEditable(true);
    }

    private void DesprotegerTutor() {
        tNombreT.setEditable(true);
       tApellido1T.setEditable(true);
       tApellido2T.setEditable(true);
       tDniT.setEditable(true);
       tCalleT.setEditable(true);
       tNumeroT.setEditable(true);
       tPisoT.setEditable(true);
       tLetraT.setEditable(true);
       tMunicipioT.setEditable(true);
       tProvinciaT.setEditable(true);
       tCodigopostalT.setEditable(true);
       tTelefono1T.setEditable(true);
       tTelefono2T.setEditable(true);
       tTelefono3T.setEditable(true);
       tTelefono4T.setEditable(true);
    }

    private Date DeStrngADate(String fechaS) {
     SimpleDateFormat sdt=new SimpleDateFormat("dd/MM/yyyy");
     Date fechaD = null;
     try{
        fechaD = (Date) sdt.parse(tfechaNacimientoP.getText());
        return fechaD;
           }catch(ParseException ex){
           ex.printStackTrace();
            return fechaD;
           }
    }
}
